### PR TITLE
Added functionality to set resource.

### PR DESCRIPTION
**Pull request by 0x747972**
You can set the resource of the client now.

### CODE REVIEW

**Comment by agl** [comment]
Is setting the resource sufficiently common that it warrants a question during setup, or is it best left as an option in the config file for those who need it enough to search for it?

If the former, can the prompt be made more helpful without making it too long? (I.e. why would I want to set a resource? What values are reasonable?)

**Comment by 0x747972** [comment]
It's rather common, I think.

Maybe on could put an example, like `Set resource? eg. "work" (Enter to skip): `
or something to that effect.

**Comment by agl** [comment]
Committed as abbf9020393e8caae3e8996a16ce48446e31cf0e

**Comment by agl** [comment]
I had to rebase your change to squash it into one commit, so GitHub won't automatically notice that it's been committed. I changed the prompt wording a little but that's all. Thanks.

**Comment by 0x747972** [comment]
Ok, thanks for accepting the pull request.

**Pull request closed without merging**
